README.md
=> Added mention to silex and removed relative path mistake

docker/resources/etc/nginx/conf.d/flyimage.conf, docker/resources/etc/nginx/nginx.conf, src/Core/Controller/CoreController.php
=> Basic cache headers for images

src/Core/Entity/Image.php, src/Core/Service/ImageManager.php
=> Fix the concurrency issue

.travis.yml, src/Core/Controller/CoreController.php, src/Core/Entity/Image.php, src/Core/Exception/AppException.php, src/Core/Exception/InvalidArgumentException.php, src/Core/Exception/MissingParamsException.php, src/Core/Exception/ReadFileException.php, src/Core/Provider/StorageProvider.php, src/Core/Resolver/ControllerResolver.php, src/Core/Service/ImageProcessor.php, src/Core/Tests/BaseTest.php, src/Core/Tests/ImageProcessorTest.php, src/Core/Tests/ImageTest.php
=> add more UnitTest

README.md, config/parameters.yml, src/Core/Controller/CoreController.php, src/Core/Entity/Image.php, src/Core/Service/ImageProcessor.php, src/Core/Tests/ImageTest.php
=> Add WebP Format Support

app.php, composer.json, composer.lock, src/Core/Controller/CoreController.php, src/Core/Controller/DefaultController.php, src/Core/Views/Default/index.twig, src/Core/Views/layout.twig, web/css/main.css
=> Make Homepage helpful, add Twig as tmpl engine

README.md
Check how it looks here:
https://github.com/flyimg/flyimg/tree/reorder-readme
=> Updated the README. Better structure and updated information.

README.md
After reading for the nºth time I still find stuff to fix.
Later I would like to re-do the demo images, to be smaller.
=> Fixing small typos in the readme and adding another demo image.

README.md, config/parameters.yml, src/Core/Controller/CoreController.php, src/Core/Controller/DefaultController.php, src/Core/Entity/Image.php, src/Core/Service/ImageProcessor.php, src/Core/Tests/ImageProcessorTest.php, src/Core/Tests/ImageTest.php
=> Add support to output png images in case source file is png

.gitignore, .travis.yml, Dockerfile, README.md, app.php, composer.json, composer.lock, config/routes.yml, src/Core/Controller/CoreController.php, src/Core/Controller/DefaultController.php, src/Core/Entity/Image.php, src/Core/Provider/StorageProvider.php
Add path action to default controller to return the full path of processed image
=> Add path action to default controller to return the full path of processed image

.travis.yml, phpunit.xml.dist
=> Add travis-ci test coverage

composer.json, composer.lock
=> Update composer [phpunittest]

src/Core/Controller/CoreController.php, src/Core/Entity/Image.php, src/Core/Handler/ImageHandler.php, tests/Core/BaseTest.php
=> Fix Code Climate warning

.gitignore, README.md, docs/enabling-xdebug.md
=> Add Xdebug Documentation

benchmark.sh
=> Add --optimize-autoloader to composer install in case of benchmark

app.php, benchmark.sh, composer.json, composer.lock, config/parameters.yml, config/routes.yml, src/Core/Resolver/RoutesResolver.php, tests/Core/Resolver/ControllerResolver.php
Remove Symfony config component
Remove monolog
=> Replace Symonfy Yaml component with php pecl yaml

app.php, config/parameters.yml, phpunit.xml.dist, src/Core/Controller/DefaultController.php, tests/Core/Controller/DefaultControllerTest.php
=> Improve logging output, remove access.log from output

config/parameters.yml, src/Core/Handler/ImageHandler.php, src/Core/Processor/ExtractProcessor.php
This works for us. Let me know if it works for you (I have not been keeping up with the changes to this repository, but it is good to see it is actively under development!)
It is basically a copy of the face crop with manual input for the coords.
=> Added option to extract part of an image

README.md
Add Community links (Github and Twitter), closes #125
=> Add Community links (Github and Twitter)

src/Core/Entity/Image/InputImage.php, src/Core/Entity/ImageMetaInfo.php, src/Core/Entity/OptionsBag.php, src/Core/Processor/ImageProcessor.php, tests/Core/Entity/Image/ImageMetaInfoTest.php, tests/Core/Entity/ImageMetaInfoTest.php, tests/Core/Processor/ImageProcessorTest.php
this is just the first steps, the failing tests, I'll start the actual refactor after this.
=> Image Processor geometry refactor.

docs/application-options.md
=> "rebuild" was missing it's "d".

docs/url-options.md
[issue-#109] Update docs about the new feature image extraction, closes #109
=> [issue-#109] Update docs about the new feature image extraction, 

src/Core/Processor/ImageProcessor.php
Fix the background color missing, closes #145
=> [issue-#145] Fix the background color missing, closes #145

README.md
This solves issue #160 .
The new domain is a more stable one I have. I'llupdate again the URLs  once I have it under https
=> Changed the domain where the source sample images are hosted. 

config/parameters.yml, docs/url-options.md, src/Core/Processor/ImageProcessor.php, tests/Core/Entity/Image/OutputImageTest.php
fix Unsharp option and add other options such as sharpen and blur, closes #202
=> fix Unsharp option and add other options such as sharpen and blur

README.md, docs/url-options.md
=> Updated the docs regarding blur, unsharp, and sharpen filters. Fixes #204

composer.lock
We got some Security Alerts from Github regarding 2 libraries used in Flyimg project.
=> Update composer, fixes #239

README.md
Added instructions and examples for pdf's and videos.
please check the urls and upload files if necessary.
=> Updated readme for PDF and video

CHANGELOG.md
Update changelog file closes #249
=> Update changelog file closes #249

src/Core/Entity/Response.php
Add Last-Modified headers tag, closes #261 
related also to #265
=> Add Last-Modified headers tag, closes #261

.github/workflows/create-tag.yml
Add new github action to release tag closes #269
=> Add new github action to release tag closes #269

.github/workflows/create-tag.yml
add empty tag_prefix for Github actions
=> add empty tag_prefix for Github actions

.github/workflows/create-tag.yml
=> Downgrade Github action to v5

.github/workflows/create-tag.yml
Add Generate ChangeLog to github action
=> Add Generate ChangeLog to github action

.github/workflows/create-tag.yml
=> Update Changelog action uses

.github/workflows/create-tag.yml
Update release branch to `main`
=> Update release branch to main

.github/workflows/create-tag.yml
=> Add code checkout step

.github/workflows/cd.yml, README.md, src/Core/Views/Default/index.html
Add deploy to demo server as part of CD, closes #280
=> Add deploy to demo server as part of CD, closes #280

.github/workflows/cd.yml
Fix deployment action, closes #280
=> Fix deployment action, closes #280

.github/workflows/cd.yml
Fix deployment step in github action, closes #280
=> Fix deployment step in github action, closes #280

.github/workflows/cd.yml, src/Core/Views/Default/index.html
Fixing changelog generator step in github action, fixes #287
=> Fixing changelog generator step in github action, fixes #287

.github/workflows/cd.yml
Fixing changelog generator in github actions, closes #287
=> Fixing changelog generator in github actions, closes #287

.github/workflows/cd.yml, .github/workflows/release.yml
create new workflow for github release, closes #287
=> create new workflow for github release, closes #287

.github/workflows/github-release.yml
Add new workflow for github release action, closes #287
=> Add new workflow for github release action, closes #287

.github/workflows/cd.yml
Fix Changlelog generator in github action workflow
=> Fix Changlelog generator in github action workflow, closes #287

.github/workflows/cd.yml, CHANGELOG.md
Fix Changelog generator in github action workflow, closes issue#287
=> Fix Changelog generator in github action workflow, closes issue#287

README.md, config/parameters.yml, src/Core/Processor/ImageProcessor.php, src/Core/Processor/Processor.php, tests/Core/Entity/Image/OutputImageTest.php
Add colorspace and monochrome options , Issue#299
=> Add colorspace and monochrome options , Issue#299

README.md, src/Core/Views/Default/index.html
=> Fixing urls, closes #301

src/Core/Entity/Image/InputImage.php
increase the max-redirect to 5 when download an image, fixing #310
=> increase the max-redirect to 5 when download an image, fixing #310

app.php, config/parameters.yml, src/Core/Controller/CoreController.php, src/Core/Entity/Response.php, src/Core/StorageProvider/LocalStorageProvider.php, src/Core/StorageProvider/S3StorageProvider.php, tests/Core/StorageProvider/S3StorageProviderTest.php
fixing issue with s3 storage_system, closes #325
=> fixing issue with s3 storage_system, closes #325

README.md, docs/url-options.md
=> Fixing Demo image link

.github/workflows/ci.yml, config/parameters.yml, docs/url-options.md, src/Core/Processor/ImageProcessor.php, tests/Core/Entity/Image/OutputImageTest.php
fixing Issue#332 by adding `auto-orient` option
=> fixing Issue#332 by adding `auto-orient` option

src/Core/Processor/ImageProcessor.php
Fixing background color options by adding `-alpha remove -alpha off`, issue #334
=> Fixing background color options by adding `-alpha remove -alpha off`

README.md, docs/full-documentation.md, docs/url-options.md
Implement Suggestions provided by EddieHubCommunity #314
=> Implement Suggestions provided by EddieHubCommunity #314

ADOPTERS.md, README.md
Add Adopters file and update readme file
=> Add Adopters file

.github/workflows/cd.yml, README.md, docs/full-documentation.md, docs/url-options.md
Replace oi.flyimg.io by demo.flyimg.io
=> Replace oi by demo subdomain

.github/workflows/close_inactive_issues.yml
Add workflow to close inactive issues
=> Add workflow to close inactive issues

.github/workflows/ci.yml
Update codecov/codecov-action to v3
=> Update codecov/codecov-action to v3

.github/workflows/cd.yml, .github/workflows/ci.yml
Upgrade actions checkout to v4
=> Upgrade actions checkout to v4

.github/workflows/cd.yml, .releaserc
fix: use Semantic-release for releasing and tagging
fixed #363
=> fix: use Semantic-release for releasing and tagging

.releaserc
Add missing configs for .releaserc file, closes #363
=> Add missing configs for .releaserc file, closes #363

.github/workflows/cd.yml
fix: use PAT in github action in cd workflow
=> fix: use PAT in github action cd workflow

.github/workflows/cd.yml, .releaserc, CHANGELOG.md
fix: add set to add a  github release
=> fix: add set to add a  github release

.github/workflows/cd.yml, CHANGELOG.md
fix: fix missing variable env. to get the next release version
=> fix: fix missing variable env. to get the next release version

.github/FUNDING.yml, .github/workflows/cd.yml, .github/workflows/ci.yml, .github/workflows/close_inactive_issues.yml, CHANGELOG.md, CODE_OF_CONDUCT.md, Dockerfile, _config.yml, config/parameters.yml, config/routes.yml, docs/application-options.md, docs/enabling-xdebug.md, src/Core/Controller/CoreController.php, src/Core/Entity/OptionsBag.php, src/Core/Handler/SecurityHandler.php, tests/Core/Entity/Image/InputImageTest.php, tests/Core/Processor/ProcessorTest.php
fix: fix missing composer install cmd
=> fix: fix missing composer install cmd

ADOPTERS.md
We are proud to be the first official adopter :-)
=> Update ADOPTERS.md adding Opencity Labs

src/Core/Entity/Response.php, src/Core/Views/Default/index.html, web/css/main.css, web/js/main.js
Update the demo page, closes #382
=> Update the new demo page, add needed elements, closes #382

src/Core/StorageProvider/S3StorageProvider.php
The base library didn't provide support for third party S3 providers such as DigitalOcean and Scaleway. This pull request aims to adress that.
=> Add support for third party S3 providers

config/parameters.yml, src/Core/Entity/Response.php, src/Core/Processor/ImageProcessor.php
fixing the s3 storage system,  closing the issue#325
=> fixing the s3 storage system,  closing the issue#325 

Dockerfile
fix: fixing facedetect issue for AVIF format images, closes #412
=> fix: fixing facedetect issue for AVIF format images, closes #412

.github/workflows/cd.yml
fix: fixing Multi-platform image with GitHub Actions
=> fix: fixing Multi-platform image with GitHub Actions

.github/workflows/cd.yml
fix: fixing the base image path for CD Github Actions
=> fix: fixing the base image path

.github/workflows/cd.yml
fix: fixing the REGISTRY_IMAGE tags
=> fix: fixing the REGISTRY_IMAGE tags

.github/workflows/cd.yml, .github/workflows/ci.yml
Fixing Upload artifact while building and pushing docker image in Github Action CD, Issue#414
=> Fixing Upload artifact while building and pushing docker image in Github Action CD, Issue#414

.github/workflows/cd.yml, CHANGELOG.md
fixing typo in docker Create manifest list and push step, Issue#414
=> fixing typo in docker Create manifest list and push step, Issue#414

.github/workflows/cd.yml, CHANGELOG.md
fix: fixing workflow release issue
=> fix: fixing workflow release issue

.github/workflows/cd.yml, CHANGELOG.md
fix: fixing Create manifest list stage
=>  fix: fixing Create manifest list stage

.github/workflows/cd.yml, CHANGELOG.md
Fxing github workflow to allow Multi-platform image push
=> fix: fixing github workflow

.github/workflows/cd.yml
adding linux/arm64/v8 platform
=> fix: adding linux/arm64/v8 platform

.github/workflows/branch-dev-deploy.yml
👋 Hey folks! I am the creator and main maintainer for the branch-deploy Action. I saw that you were using it and wanted to bring in some improvements.
I have done the following:
- Upgraded to `v9`. It should be safe for you to do so in this project (I checked)
- Added a more specific `if:` block to help prevent excess Actions workflows to trigger when folks leave comments on PRs that don't contain `.deploy` style commands
- Added an extra permissions statement (only really applies to private repos but its safe to add here)
=> Update branch deployments

tests/Core/Entity/Image/InputImageTest.php, tests/Core/Entity/Image/OutputImageTest.php, tests/Core/Entity/ImageMetaInfoTest.php, tests/Core/Processor/ImageProcessorTest.php
Fixing UnitTests Deprecations warnings, closes #441
=> Fixing UnitTests Deprecations warnings, closes #441

README.md
=> chore: add Star History image

config/parameters.yml, docs/application-options.md, web/js/main.js
Add OPTIONS_SEPARATOR to js code, fixing #449
=> fix: add options_separator to js code

docs/application-options.md, src/Core/StorageProvider/S3StorageProvider.php
Hi.
Great project.
I've added some extra S3 parameters to complete the Minio support.
(And one missing parameter from another PR in the doc)
=> Additional S3 parameters.

.github/workflows/cd.yml, .github/workflows/docs.yml, .gitignore, docs/unit-tests.md
=> Add github workflow for generating docs

README.md, docs/assets/stylesheets/extra.css, docs/basic-usage.md, docs/index.md, mkdocs.yml
Documentation updates, part of #452
=> Documentation updates

docs/assets/stylesheets/extra.css
docs: fixing logo opacity, related to issue #452
=> docs: fixing logo opacity

src/Core/Entity/Image/InputImage.php
A not so pretty fix for the encoding Problem in https://github.com/flyimg/flyimg/issues/481
=> fix problem with special characters in url

config/parameters.yml, src/Core/Entity/Image/InputImage.php
Fix Redirect URLs without protocol schema, closes #486
=> fix: Redirect URLs without protocol schema are not handled correctly

Dockerfile, cleanup-tmp.sh, config/parameters.yml, docs/configuration.md, src/Core/Entity/Image/InputImage.php
Add cleanup cron job to purge var/tmp folder, related to #484
=> fix: add cleanup cron job to purge var/tmp folder, related to Issue#484

Dockerfile, cleanup-tmp.sh
fix: use new base image version (PHP 8.3 + updated libraries versions)
and trying out new php-fpm settings `pm.max_requests = 50`
=> fix: use new base image version (php 8.3 + updated libraries versions)

config/parameters.yml, src/Core/Controller/CoreController.php, src/Core/Views/Default/index.html
add home page title as parameter, closes #492
=> add home page title as parameter, closes #492

composer.json, composer.lock, src/Core/Entity/Response.php, src/Core/StorageProvider/LocalProviderTrait.php, src/Core/StorageProvider/LocalStorageProvider.php, src/Core/StorageProvider/S3StorageProvider.php, tests/Core/Entity/ResponseTest.php, tests/Core/StorageProvider/S3StorageProviderTest.php
fix: fixing S3 not working, upgrading league/flysystem lib, closes #493
=> fix: fixing S3 not working, upgrading league/flysystem lib, closes#493

.github/workflows/cd.yml
Update cd workflow to use docker swarm instead of docker compose
=> Update cd workflow

docs/url-options.md
=> fix documentation links

.github/workflows/ci.yml, Dockerfile, config/parameters.yml, python/facedetect.py, python/requirements.txt, python/smartcrop.py, src/Core/Processor/FaceDetectProcessor.php, src/Core/Processor/Processor.php
fix: fix smart crop feature, use new base image version, closes #500
=> fix: fix smart crop feature, use new base image version

docs/helm-chart.md, mkdocs.yml
add helm chart documentation, closes #398
=> add helm chart documentation

Dockerfile, cleanup-tmp.sh
fix: fix the issue of tmp folder permission, closes #506
=> fix: fix the issue of tmp folder permission, closes #506

docs/helm-chart.md, docs/index.md, docs/url-options.md
Updating the documentation, closing Issue#509
=> Updating the documentation, closing Issue#509

README.md
Update Readme file: change Star history location, related to #509
=> Update Readme file: change Star history location

src/Core/Processor/ImageProcessor.php
fixing Cropping Image Changes Transparent Background To Solid Color related to #514
=> fix: fixing Cropping Image Changes Transparent Background To Solid Color

composer.lock
chore(release): composer update run, closed #524
=> chore(release): composer update run, closed #524

.github/workflows/cd.yml
fix: fix the incorrect version shown in the footer, closes #528
=> fix: fix incorrect version shown in footer

.github/workflows/branch-dev-deploy.yml, .github/workflows/cd.yml, .github/workflows/ci.yml
fix: fix Github workflow, closes #543
=> fix: fix Github workflow, closes #543

python/facedetect.py, python/smartcrop.py
fix: refactor python code for the smartcrop and facedetect, remove unused features
=> fix: refactor python to remove unused code

README.md, composer.json, docs/index.md
chore(release): update docs for AGPL license, closes #546
=> chore(release): update docs for AGPL license

src/Core/Processor/ImageProcessor.php
fix: fix Gravity value is ignored and crop always uses West, related to #561
=> fix: fix Gravity value is ignored and crop always uses West

CNAME
update CNAME to docs.flyimg.io
=> update CNAME to docs.flyimg.io

config/parameters.yml, docs/configuration.md, src/Core/Controller/CoreController.php, src/Core/Views/Default/index.html, web/css/main.css, web/js/main.js
fix: add dynamic URL support and copy functionality to the example code snippet
related to #570
=> fix: add dynamic URL support and copy functionality to example code

mkdocs.yml
=> chore: update documentation gtag

.github/workflows/docs.yml, mkdocs.yml
=> chore: update docs workflow ci

config/parameters.yml, docs/configuration.md, src/Core/Controller/DefaultController.php, tests/Core/Controller/DefaultControllerTest.php
fix: add the possibility to enable or disable the default demo page
#581
=> fix: add the possibility to enable or disable the default demo page
